[package]
name = "smt"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
rocksdb = { workspace = true }
blake3 = { workspace = true }
kanari-db-common = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }

[features]
default = []
blake3 = []

[dev-dependencies]
tempfile = { workspace = true }