[package]
name = "centauri"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
hex = { workspace = true }
kanari-types = { workspace = true }
kanari-crypto = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }
smt = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }
ed25519-dalek = { workspace = true }
curve25519-dalek = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }
rayon = "1.10"
num_cpus = "1.16"

[dev-dependencies]
tempfile = "3.8"
