[package]
name = "centauri"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
hex = { workspace = true }
kanari-types = { workspace = true }
kanari-crypto = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }
smt = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }
ed25519-dalek = { workspace = true }
curve25519-dalek = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }
rayon = { workspace = true }
log = { workspace = true }
num_cpus = "1.17.0"
moka = { version = "0.12.15", features = ["sync"] }
siphasher = "1.0.2"
tokio = { workspace = true, features = ["full"] }
dashmap = "6.1.0"
ahash = "0.8.12"

[dev-dependencies]
tempfile = { workspace = true }
