[workspace]
# Workspace configuration for the "kanari-sdk" project.
# Defines the overall structure and settings for the workspace.
# name = "kanari-sdk"
resolver = "2"                   # Use the version 2 feature resolver for more consistent feature resolution.

# Exclude List: Directories to be excluded from the workspace build.
# This can be useful for excluding third-party code or components 
# that are not directly part of the workspace's build process.
exclude = [
    "third_party/move"           # Exclude the 'third_party/move' directory from workspace builds.
]

# Members List: Crates that are part of this workspace.
# These are the core components of the "kanari-" project.
members = [
      "crates/kanari",
      "crates/kanari-common",
      "crates/kanari-crypto", 
      "crates/kanari-framework-builder",
      "crates/kanari-frameworks", 
      "crates/kanari-move-runtime", 
      "crates/kanari-types",
      "crates/kanari-node",
      "crates/kanari-rpc-api", 
      "crates/kanari-rpc-client", 
      "crates/kanari-rpc-server",
      "crates/kanari-faucet",
      "packages/kanari_flutter/rust",
      "crates/kanari-core",
      "crates/smt",
      "crates/tps-harness", 
      "crates/kanari-system-natives",
      "crates/kanari-db-common", 
      "crates/centauri", 
      "sdk/wallet",
]

# Workspace Package Configuration: Metadata for the entire workspace as a package.
# This information is used when publishing the SDK as a crate.
[workspace.package]
edition = "2024"                                                                                                   # Use Rust 2024 edition.
categories = ["development-tools"]                                                                                 # Categorize as development tools on crates.io.
keywords = ["blockchain", "sdk", "move", "monaOS", "monaVM", "rust", "ifps", "storage", "wallet", "framework"]     # Keywords for crates.io search.
homepage = "https://kanari.network"                                                                                # Project homepage.
documentation = "https://docs.kanari.network"                                                                      # Link to project documentation.
version = "0.1.5"                                                                                                  # Current version of the SDK.
authors = ["Kanari Network"]                                                                                       # Authors of the SDK.
license = "Apache-2.0"                                                                                             # License information.
repository = "https://github.com/kanari-network/kanari-sdk"                                                        # Link to the code repository.
description = "Kanari Network SDK"                                                                                 # Short description of the SDK.


# Dependencies that should be kept in sync through the whole workspace
[workspace.dependencies]

# Runtime & async
tokio = { version = "1.49.0", features = ["full"] }

# Networking / HTTP / Web
reqwest = { version = "0.13.2", features = ["json"] }
axum = "0.8.7"
tower-http = { version = "0.6.8", features = ["cors"] }

# Database / storage
rocksdb = "0.24.0"

# Serialization / config
serde = { version = "1.0.228", default-features = true }
serde_json = { version = "1.0.149", default-features = true }
serde_yaml = { version = "0.9.34-deprecated", default-features = true }
toml = { version = "0.9.8", default-features = true }
bcs = { version = "0.1.6" }
bincode = { version = "2.0.1", features = ["serde", "alloc"] }

# Cryptography - classical
sha2 = "0.10.9"
sha3 = "0.10.8"
hex = "0.4.3"
primitive-types = { version = "0.14.0", default-features = true }
argon2 = { version = "0.5.3", default-features = true }
hmac = { version = "0.12.1" }

k256 = { version = "0.13.4", features = ["ecdsa", "std"] }
p256 = { version = "0.13.2", features = ["ecdsa", "std"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
curve25519-dalek = { version = "4", features = ["rand_core"] }
secp256k1 = { version = "0.31.1", features = ["recovery"] }
aes-gcm = "0.10.3"
base64 = "0.22.1"
zstd = "0.13.3"
lru = "0.16.3"
# HD wallet / key derivation
bip39 = { version = "2.2.2", features = ["rand"] }
bip32 = "0.5.3"

# Memory security
zeroize = { version = "1.8.1", features = ["derive"] }
rpassword = "7.4.0"
fs2 = "0.4.3"

# Post-Quantum Cryptography (PQC)
pqcrypto-dilithium = "0.5"
pqcrypto-kyber = "0.8.1"
pqcrypto-sphincsplus = "0.7.2"
pqcrypto-traits = "0.3.5"
rayon = "1.11.0"
# Optional hashing
blake3 = { version = "1.8.3" }

# CLI / tooling / utilities
clap = { version = "4.5.57", features = ["derive"] }
dirs = "6.0.0"
walkdir = "2.5.0"
tempfile = "3.24.0"
smallvec = "1.15.1"
lazy_static = { version = "1.5.0", default-features = true }
once_cell = "1.20.0"
crossbeam-channel = "0.5.15"
num_cpus = "1.17.0"

# Randomness, error handling
rand = "0.8.5"
anyhow = "1.0.101"
thiserror = { version = "2.0.18", default-features = true }
better_any = "0.1.1"

# Logging & tracing
log = { version = "0.4.28", default-features = true }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
env_logger = "0.11.8"

# Time
chrono = "0.4.43"

kanari-common = { path = "crates/kanari-common" }
kanari-crypto = { path = "crates/kanari-crypto" }
kanari-types = { path = "crates/kanari-types" }
kanari-move-runtime = { path = "crates/kanari-move-runtime" }
kanari-framework-builder = { path = "crates/kanari-framework-builder" }
kanari-frameworks = { path = "crates/kanari-frameworks" }
kanari-rpc-api = { path = "crates/kanari-rpc-api" }
kanari-rpc-client = { path = "crates/kanari-rpc-client" }
kanari-rpc-server = { path = "crates/kanari-rpc-server" }
kanari-faucet = { path = "crates/kanari-faucet" }
kanari-core = { path = "crates/kanari-core" }
kanari-system-natives = { path = "crates/kanari-system-natives" }
kanari-db-common = { path = "crates/kanari-db-common" }

# SMT Support
smt = { path = "crates/smt" }
centauri = { path = "crates/centauri" }

# Move dependencies
move-binary-format = { path = "third_party/move/crates/move-binary-format" }
move-bytecode-utils = { path = "third_party/move/crates/move-bytecode-utils" }
move-bytecode-source-map = { path = "third_party/move/crates/move-bytecode-source-map" }
move-cli = { path = "third_party/move/crates/move-cli" }
move-compiler = { path = "third_party/move/crates/move-compiler" }
move-core-types = { path = "third_party/move/crates/move-core-types" }
move-disassembler = { path = "third_party/move/crates/move-disassembler" }
move-package = { path = "third_party/move/crates/move-package" }
move-unit-test = { path = "third_party/move/crates/move-unit-test" }
move-vm-config = { path = "third_party/move/crates/move-vm-config" }
move-vm-test-utils = { path = "third_party/move/crates/move-vm-test-utils/", features = [
  "tiered-gas",
] }
move-vm-types = { path = "third_party/move/crates/move-vm-types" }
move-vm-profiler = { path = "third_party/move/crates/move-vm-profiler" }
move-command-line-common = { path = "third_party/move/crates/move-command-line-common" }
move-transactional-test-runner = { path = "third_party/move/crates/move-transactional-test-runner" }
move-ir-types = { path = "third_party/move/crates/move-ir-types" }
move-prover = { path = "third_party/move/crates/move-prover" }
move-stackless-bytecode = { path = "third_party/move/crates/move-stackless-bytecode" }
move-symbol-pool = { path = "third_party/move/crates/move-symbol-pool" }
move-abstract-stack = { path = "third_party/move/crates/move-abstract-stack" }
move-docgen = { path = "third_party/move/crates/move-docgen" }
move-errmapgen = { path = "third_party/move/crates/move-errmapgen" }
move-stdlib = { path = "third_party/move/crates/move-stdlib" }
move-stdlib-natives = { path = "third_party/move/crates/move-stdlib-natives" }

move-vm-runtime = { path = "third_party/move/crates/move-vm-runtime" }
move-coverage = { path = "third_party/move/crates/move-coverage" }
move-bytecode-verifier = { path = "third_party/move/crates/move-bytecode-verifier" }


# Profile Configurations: Define different build profiles for various scenarios.
[profile.bench]                  # Profile for benchmarking.
debug = true                     # Include debug information for profiling.
opt-level = 3                    # Maximum optimization level for performance.
lto = "thin"                     # Enable Link-Time Optimization (thin LTO for faster linking).
codegen-units = 1                # Reduce codegen units to improve LTO effectiveness (may increase compile time).

[profile.dev]                    # Profile for development builds.
debug = false                    # Disable debug information for easier debugging.
opt-level = 0                    # No optimization for faster compile times.
split-debuginfo = "unpacked"     # Configure debug info splitting for better debugger experience.
debug-assertions = true          # Enable debug assertions for development builds.
overflow-checks = true           # Enable overflow checks for development builds.
lto = false                      # Disable Link-Time Optimization for faster builds.
panic = 'unwind'                 # Enable unwinding for panic handling.
incremental = true               # Enable incremental compilation for faster builds.
codegen-units = 256              # Increase codegen units for faster parallel compilation.

[profile.ci]                     # Profile for Continuous Integration builds.
inherits = "test"                # Inherit settings from the 'test' profile (if defined, otherwise defaults).
debug = 0                        # Disable debug information for potentially faster and smaller builds.
incremental = false              # Disable incremental compilation for cleaner and more reliable CI builds.
codegen-units = 16               # Increase codegen units for potentially faster parallel compilation in CI.
opt-level = 1                    # Moderate optimization level for a balance of speed and performance.

[profile.release]                # Profile for release builds.
opt-level = 'z'                  # Optimize for size.
debug = false                    # Disable debug information for release binaries.
debug-assertions = false         # Disable debug assertions for release builds.
overflow-checks = false          # Disable overflow checks for release builds.
lto = true                       # Enable full Link-Time Optimization for maximum performance and smaller binaries.
panic = 'abort'                  # Remove unwinding code for panic handling.
codegen-units = 1                # Reduce codegen units to improve LTO effectiveness.
strip = true                     # Strip debug symbols from the final binary to reduce size.
