[package]
name = "kanari-open-rpc-spec-builder"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
kanari-open-rpc = { workspace = true }
kanari-open-rpc-spec = { workspace = true }
kanari-rpc-api = { workspace = true }
