// Copyright (c) KanariNetwork, Inc.
// SPDX-License-Identifier: Apache-2.0

/// End-to-end fixtures for `kanari_system::zklogin`, generated by
/// `kanari-crypto/src/signatures/fixture_gen_tmp.rs` (deterministic):
/// - ephemeral key from secret `[42u8; 32]`, message "kanari ephemeral fixture"
/// - JWT minted RS256 with kid `kanari-fixture-1`, nonce bound to the
///   ephemeral key above (pub, max_epoch 1000, randomness `[7u8; 32]`)
/// - MulCircuit (6*7=42) Groth16 proof, seed `0x5eed42`
#[test_only]
module kanari_system::zklogin_tests {
    use kanari_system::zklogin;

    fun iss(): vector<u8> { b"https://accounts.google.com" }
    fun aud(): vector<u8> { b"kanari-test-client" }
    fun sub(): vector<u8> { b"1234" }
    const NOW: u64 = 1700000000;

    fun eph_pub(): vector<u8> {
        x"197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d61"
    }

    fun eph_msg(): vector<u8> {
        b"kanari ephemeral fixture"
    }

    fun eph_sig(): vector<u8> {
        x"50bd675ac9206bafbbec36010d5ef5b902e25aaa8cbd11c6d8626e2f105487df6eb7273c7ad5acda84a422df9bf45e9ecfc0461d33ecae5035ebeee33aa8ba05"
    }

    fun randomness(): vector<u8> {
        x"0707070707070707070707070707070707070707070707070707070707070707"
    }

    fun salt(): vector<u8> {
        x"0909090909090909090909090909090909090909090909090909090909090909"
    }

    fun jwt(): vector<u8> {
        b"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImthbmFyaS1maXh0dXJlLTEifQ.eyJhdWQiOiJrYW5hcmktdGVzdC1jbGllbnQiLCJleHAiOjIwMDAwMDAwMDAsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbSIsIm5vbmNlIjoiMWJiNDg2YzAyZGVlZjBhNGFjY2Y1ZjdjNGNhMmU3ZTU0Y2UxOGNiMTNiN2ZhNGUxOTMzOThlYmUxYjg1ODBmYiIsInN1YiI6IjEyMzQifQ.Ivv6o1AWQ2b4vOQauAd7-cg1PH6E-MCoTb3QlNPCgvVZSEk2bRVsxtwOu_FkXON2336ZxxA3oJaKKCi1uEKLMIxw1rf_RE-fNEn8kmW9sgZZZTJGiFx2W9YMB6-xHP5vJJiFVGyH8SgjPAwHCkct9DA3Q1N3k1o_IIkYPukRuo20X-8utI7JsZ6GkKgzNwQnaJKbzRiG4jBr6CqwLKTlAYPWi15IxtXZrYvO64g2iTW5vHGyOXzUyUn0c1vwdYgCiiMjdbHIBx-6mK8fBaD18YeiLf97viQhLwQS2ydM-hFZv970UsDa3574ig2YMV5ILW2fhOSJiqEf7ri_6SAgPg"
    }

    fun jwks(): vector<u8> {
        b"{\"keys\":[{\"kty\":\"RSA\",\"kid\":\"kanari-fixture-1\",\"alg\":\"RS256\",\"n\":\"mm_L6UcI9QJow4_cr4lKVKk-TI5flT1JKUZn-RSdF9dykE99UfBoCjOd9GAjjcyzmLU2nQ1d3NxmmnM79yMA9AJCR17PH7F1T5D1sBH6ljnst2b0qmdCH6ocvHoHYo7eG3dNjkX8OgK2a5_rQWtuAbh9r5GBGz5MqkkQl16NAdsLoTNNN6JpXl-UgmKuaCrjYTBlQEbclVY6exgC1EV5zKwnd6dq44czYJUlzJt5nEdU_0P429OTu6o6XuxAB0B6bxeqg3-SPHTXtdzEfykUsNXMF4dKrbYZTboj6b2Ic4gqfC6aiEB5Et8iQQrON5c87yOERRspyOnywaAlzS92RQ\",\"e\":\"AQAB\"}]}"
    }

    fun vk(): vector<u8> {
        x"82c7650612310fe5a29b5698669464a007ce19f534b5ddff7837f58f720f249c06b90575d040e7f698f7e53952956944496f617567f2c85efe42d4759efcea24cad069dc0de9b8fa6f8a2f9ce9043c51d487d5cab13267833f1e21d7a401c82a9e7a216f39b2b92cfed21cdf5f96c620adbee2c46bd6b071e5da9254ceac5d2ff69aa1314ba3958de6efc3c2bb9b10fc1f81171820d6a7c40fab8a123094a5a45d72fea4062cdabc3e6a2e5f134c17b52ce8fc2dcb6e291a2662bae07c37851b118847ddcca2a0f59da213f6af026881dd9a482e7457684e936e010319e8cc2e0200000000000000372030c8127c63a873320fa113a3f51cd0e9595dd556dafee44dafc53e33861783d5c4c6285c2a11fa4493b65564bec77993e4821f79e70e949e8eca4cdda203"
    }

    fun proof_inputs(): vector<u8> {
        x"000000000000000000000000000000000000000000000000000000000000002a"
    }

    fun proof(): vector<u8> {
        x"0ee2357e2cff03ef231a6fccb79d332460c45f8cae6160e9ca6d222f34225323a4b19193fac8e96459996554fb5a5904fefeb15d9848f128191a819a88ed760872151f9d5d5a37734257d0fa05be359e4580cbfe3f640561cd50fdd62c098f11f2689ae9487732d852acb3a8e2149d8de12ceb8b9ab0c2790def100a1ed1de96"
    }

    // =================================================================
    // JWT path (Phase 3b)
    // =================================================================

    #[test]
    fun test_verify_jwt_accepts_fixture() {
        assert!(zklogin::verify(&jwt(), &jwks(), &iss(), &aud(), NOW), 0);
    }

    #[test]
    #[expected_failure(abort_code = 5)]
    fun test_verify_jwt_wrong_aud_aborts() {
        // NOTE: native maps signature/aud failures to E_EXPIRED(5), not
        // E_CLAIM_MISMATCH — locked here so any change is deliberate.
        zklogin::verify(&jwt(), &jwks(), &iss(), &b"someone-else", NOW);
    }

    #[test]
    fun test_check_nonce_accepts_fixture() {
        assert!(zklogin::check_nonce(&jwt(), &eph_pub(), 1000, &randomness()), 0);
        // Wrong epoch changes the binding.
        assert!(!zklogin::check_nonce(&jwt(), &eph_pub(), 999, &randomness()), 1);
    }

    #[test]
    fun test_derive_address_matches_rust() {
        let addr = zklogin::derive_address(&iss(), &aud(), &sub(), &salt());
        assert!(addr == x"7e38f84e6dc09858495a1bd83a6a043fe9b822faf7399b828d2a5b41d652117b", 0);
    }

    // =================================================================
    // Ephemeral path (pop-order regression test)
    // =================================================================

    #[test]
    fun test_verify_ephemeral_accepts_fixture() {
        // Declared order is (sig, pk, msg) — matching native pop order.
        assert!(zklogin::verify_ephemeral(&eph_sig(), &eph_pub(), &eph_msg()), 0);
    }

    #[test]
    #[expected_failure(abort_code = 3)]
    fun test_verify_ephemeral_swapped_order_aborts() {
        // The old, misleading order (pk, msg, sig) puts a 24-byte message
        // where the 32-byte pubkey goes: the Move length guard aborts
        // instead of mis-verifying. This locks the pop order in.
        zklogin::verify_ephemeral(&eph_pub(), &eph_msg(), &eph_sig());
    }

    #[test]
    fun test_verify_session_full_combo() {
        assert!(
            zklogin::verify_session(
                &jwt(),
                &jwks(),
                &iss(),
                &aud(),
                NOW,
                &eph_pub(),
                1000,
                &randomness(),
                &eph_msg(),
                &eph_sig(),
            ),
            0,
        );
    }

    // =================================================================
    // Groth16 path (Phase 3c)
    // =================================================================

    #[test]
    fun test_verify_proof_accepts_fixture() {
        assert!(zklogin::verify_proof(&vk(), &proof_inputs(), &proof()), 0);
        // Same proof, wrong public input (c=43): well-formed but false.
        let bad = x"000000000000000000000000000000000000000000000000000000000000002b";
        assert!(!zklogin::verify_proof(&vk(), &bad, &proof()), 1);
    }

    #[test]
    fun test_verify_private_session_combo() {
        assert!(
            zklogin::verify_private_session(
                &vk(),
                &proof_inputs(),
                &proof(),
                &eph_pub(),
                &eph_msg(),
                &eph_sig(),
            ),
            0,
        );
    }
}
