[package]
name = "kanari-indexer"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
# Internal crates
kanari-types = { workspace = true }

# Database
rusqlite = { workspace = true }

# Serialization
serde = { workspace = true }
bcs = { workspace = true }
hex = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }

# Utilities - enable serde feature for DateTime serialization
chrono = { workspace = true, features = ["serde"] }

[dev-dependencies]
tracing-subscriber = { workspace = true }
