[package]
name = "kanari"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["full"] }

# Serialization
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Logging
log = { workspace = true }

reqwest = { workspace = true, features = ["blocking", "json"] }

# Cryptography
hex = { workspace = true }

# CLI
clap = { workspace = true, features = ["derive"] }

# Local dependencies
kanari-crypto = { workspace = true }
kanari-types = { workspace = true }
kanari-rpc-client = { workspace = true }
kanari-rpc-api = { workspace = true }
kanari-common = { workspace = true }
kanari-faucet = { path = "../kanari-faucet" }

# Move dependencies
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-compiler = { workspace = true }
move-command-line-common = { workspace = true }
move-docgen = { workspace = true }
move-package = { workspace = true }
move-coverage = { workspace = true }
move-vm-test-utils = { workspace = true }
move-unit-test = { workspace = true }

bcs = { workspace = true }
move-stdlib-natives = { workspace = true }
kanari-system-natives = { workspace = true }
rpassword = { workspace = true }

[features]
default = []

[[bin]]
name = "kanari"
path = "src/main.rs"
