[package]
name = "kanari-node"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
kanari-core = { workspace = true }
kanari-rpc-server = { workspace = true }
kanari-types = { workspace = true }
kanari-crypto = { workspace = true }
centauri = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
libp2p = { version = "0.56.0", features = ["tcp", "noise", "yamux", "gossipsub", "mdns", "kad", "identify", "macros", "tokio", "relay", "dcutr", "ping"] }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
tempfile = { workspace = true }

[profile.dev]
opt-level = 0
