[book]
authors = ["jamesatomc"]
language = "en"
multilingual = false
src = "src"
title = "whitepaper Kanari SDK"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/kanari-network/kanari-sdk"
edit-url-template = "https://github.com/kanari-network/kanari-sdk/edit/main/documentation/whitepaper/{path}"
site-url = "/kanari-sdk/"
cname = "whitepaper.kanari.network"
mathjax-support = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3