[build]
jobs = 8  # Adjust to match your CPU core count
incremental = true

rustflags = [
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-W", "clippy::nursery"
]

[target.'cfg(debug_assertions)']
rustflags = [
    "-W", "clippy::dbg_macro",
    "-W", "clippy::print_stdout",
]

[target.x86_64-unknown-linux-gnu]  # Adjust target as needed
rustflags = ["-C", "target-cpu=native"]

[net]
git-fetch-with-cli = true  # Can be faster for git dependencies

[alias]
a = "add"
au = "audit"
b = "build"
br = "build --release"
c = "check"
cl = "clean"
d = "doc --open"
r = "run"
rr = "run --release"
up = "update"

kb = "build -p kari"                # Build kari package
kbr = "build -p kari --release"     # Build kari package in release mode
kr = "run -p kari"                  # Run kari package
krr = "run -p kari --release"       # Run kari package in release mode