[package]
name = "kari"
edition.workspace = true
version.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
colored.workspace = true
chrono.workspace = true
tokio.workspace = true

# This is a workspace crate, so we need to include the following dependencies
mona-crypto.workspace = true
mona-blockchain.workspace = true
panorama.workspace = true 
command.workspace = true
