[package]
name = "KanariSystem"
edition = "legacy" # edition = "legacy" to use legacy (pre-2024) Move


[dependencies]
KanariFramework = { local = "../../../framework/packages/kanari-framework" }
MoveStdlib = { local = "../../../framework/packages/move-stdlib" }


[addresses]
kanari_system = "0x3"

