[package]
name = "kanari-core"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
move-core-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
hex = { workspace = true }
kanari-move-runtime = { workspace = true }
kanari-types = { workspace = true }
kanari-crypto = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }
crossbeam-channel = { workspace = true }
num_cpus = { workspace = true }
smt = { workspace = true }
tracing = { workspace = true }
lru = "0.16.2"
sha3 = { workspace = true }
zstd = "0.13"
ed25519-dalek = "2.2.0"
rand = "0.8.5"
bls-signatures = "0.15.0"
rocksdb = "0.24.0"
