name: Lint
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  pr-title:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Check PR title format
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          fetch-depth: 0
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # pin@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  formatting:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # pin@v7.0.0
        with:
          python-version: "3.x"
      - name: Install and run editorconfig-checker
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install editorconfig-checker=="2.7.3"
          ec
      - name: Install taplo
        run: |
          url="https://github.com/tamasfe/taplo/releases/download/0.9.3/taplo-linux-x86_64.gz"
          curl -sSL "$url" | gunzip > taplo
          chmod +x taplo
      - name: Check formatting of all TOML files
        run: ./taplo format --check
      - name: Install yamlfmt
        run: |
          url="https://github.com/google/yamlfmt/releases/download/v0.17.0/yamlfmt_0.17.0_Linux_x86_64.tar.gz"
          curl -sSL "$url" | tar xvz yamlfmt
      - name: Check formatting of all YAML files
        run: ./yamlfmt -lint
  typos:
    runs-on: ubuntu-latest
    name: Check spelling
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
      - uses: crate-ci/typos@4d9c206a77c041268485162b8e2579ad7a5cb9a3 # pin@v1.50.0
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
      - name: Run ShellCheck
        run: find . -type f -name "*.sh" -exec shellcheck --severity=error {} +
  license-headers:
    runs-on: ubuntu-latest
    name: Check license headers
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
      - name: Install licensesnip
        uses: taiki-e/install-action@742a3317eac7bd62f91cd888b4eead5e784ba833 # pin@v2.87.1
        with:
          tool: licensesnip@1.7.0
      - run: licensesnip check
  check-all:
    name: Check if all lint jobs succeeded
    if: always()
    needs:
      - pr-title
      - formatting
      - typos
      - shellcheck
      - license-headers
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether all needed jobs succeeded
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # pin@v1.3.0
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
