[package]
name = "p2p-protocol"
edition.workspace = true
version.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Peer-to-peer networking protocol for Kanari blockchain"

[dependencies]
tokio.workspace = true
serde.workspace = true
bincode.workspace = true
log.workspace = true
serde_json.workspace = true
lazy_static.workspace = true
rand.workspace = true
hex.workspace = true

# Kanari dependencies
mona-blockchain.workspace = true
mona-crypto.workspace = true
consensus-pos.workspace = true
common.workspace = true
