[package]
name = "kanari-db-common"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
rocksdb = { workspace = true }
once_cell = { workspace = true }
dirs = { workspace = true }

[features]
default = []
