// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_curve_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

/// Generate a keypair for the specified curve type
Future<KeyPairData> generateKeypairApi({required String curveName}) =>
    RustLib.instance.api.crateApiGenerateKeypairApi(curveName: curveName);

/// Derive a keypair from a mnemonic (BIP39)
Future<KeyPairData> deriveKeypairFromMnemonic({
  required String mnemonic,
  required String curveName,
}) => RustLib.instance.api.crateApiDeriveKeypairFromMnemonic(
  mnemonic: mnemonic,
  curveName: curveName,
);

/// Import a keypair from a provided private key
Future<KeyPairData> importKeypairFromPrivateKey({
  required String privateKey,
  required String curveName,
}) => RustLib.instance.api.crateApiImportKeypairFromPrivateKey(
  privateKey: privateKey,
  curveName: curveName,
);

/// Sign a message
Future<Uint8List> signMessageApi({
  required String privateKey,
  required List<int> message,
  required String curveName,
}) => RustLib.instance.api.crateApiSignMessageApi(
  privateKey: privateKey,
  message: message,
  curveName: curveName,
);

/// Verify a signature
Future<bool> verifySignatureApi({
  required String address,
  required List<int> message,
  required List<int> signature,
  required String curveName,
}) => RustLib.instance.api.crateApiVerifySignatureApi(
  address: address,
  message: message,
  signature: signature,
  curveName: curveName,
);

/// Generate a random mnemonic
Future<String> generateMnemonicApi({required BigInt wordCount}) =>
    RustLib.instance.api.crateApiGenerateMnemonicApi(wordCount: wordCount);

/// Derive a keypair from a mnemonic at a specific derivation path
Future<KeyPairData> deriveKeypairFromPathApi({
  required String mnemonic,
  required String derivationPath,
  required String curveName,
}) => RustLib.instance.api.crateApiDeriveKeypairFromPathApi(
  mnemonic: mnemonic,
  derivationPath: derivationPath,
  curveName: curveName,
);

/// Derive multiple addresses from a mnemonic using a path template
Future<List<KeyPairData>> deriveMultipleAddressesApi({
  required String mnemonic,
  required String pathTemplate,
  required String curveName,
  required BigInt count,
}) => RustLib.instance.api.crateApiDeriveMultipleAddressesApi(
  mnemonic: mnemonic,
  pathTemplate: pathTemplate,
  curveName: curveName,
  count: count,
);

/// List all supported curves
Future<List<CurveInfo>> listSupportedCurves() =>
    RustLib.instance.api.crateApiListSupportedCurves();

/// Expose curve names safely for Dart
class CurveInfo {
  final String name;
  final bool isPostQuantum;
  final bool isHybrid;
  final int securityLevel;

  const CurveInfo({
    required this.name,
    required this.isPostQuantum,
    required this.isHybrid,
    required this.securityLevel,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      isPostQuantum.hashCode ^
      isHybrid.hashCode ^
      securityLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurveInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isPostQuantum == other.isPostQuantum &&
          isHybrid == other.isHybrid &&
          securityLevel == other.securityLevel;
}

/// KeyPair data structure safe for FFI transfer
class KeyPairData {
  final String privateKey;
  final String publicKey;
  final String address;
  final Uint8List rawPublicKey;
  final String curveType;

  const KeyPairData({
    required this.privateKey,
    required this.publicKey,
    required this.address,
    required this.rawPublicKey,
    required this.curveType,
  });

  @override
  int get hashCode =>
      privateKey.hashCode ^
      publicKey.hashCode ^
      address.hashCode ^
      rawPublicKey.hashCode ^
      curveType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPairData &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey &&
          address == other.address &&
          rawPublicKey == other.rawPublicKey &&
          curveType == other.curveType;
}
