// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1279237213;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: '../../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiBlake3HashApi({required List<int> data});

  Future<KeyPairData> crateApiDeriveKeypairFromMnemonic({
    required String mnemonic,
    required String curveName,
  });

  Future<KeyPairData> crateApiDeriveKeypairFromPathApi({
    required String mnemonic,
    required String derivationPath,
    required String curveName,
  });

  Future<KeyPairData> crateApiDeriveKeypairFromSeedApi({
    required List<int> seed,
    required String curveName,
  });

  Future<List<KeyPairData>> crateApiDeriveMultipleAddressesApi({
    required String mnemonic,
    required String pathTemplate,
    required String curveName,
    required BigInt count,
  });

  Future<KeyPairData> crateApiGenerateKeypairApi({required String curveName});

  Future<String> crateApiGenerateMnemonicApi({required BigInt wordCount});

  Future<KeyPairData> crateApiImportKeypairFromPrivateKey({
    required String privateKey,
    required String curveName,
  });

  Future<List<CurveInfo>> crateApiListSupportedCurves();

  Future<Uint8List> crateApiSignMessageApi({
    required String privateKey,
    required List<int> message,
    required String curveName,
  });

  Future<bool> crateApiVerifySignatureApi({
    required String address,
    required List<int> message,
    required List<int> signature,
    required String curveName,
  });

  Future<Uint8List> crateApiZkloginBuildBundle({
    required String jwt,
    required String jwksJson,
    required String iss,
    required String aud,
    required List<int> salt,
    required List<int> randomness,
    required List<int> ephemeralPubkey,
    required List<int> ephemeralSig,
    required BigInt maxEpoch,
  });

  Future<String> crateApiZkloginDeriveAddress({
    required String iss,
    required String aud,
    required String sub,
    required List<int> salt,
  });

  Future<Uint8List> crateApiZkloginDeterministicSalt({
    required String iss,
    required String aud,
    required String sub,
  });

  Future<ZkLoginNonceData> crateApiZkloginPrepareNonce({
    required BigInt maxEpoch,
  });

  Future<Uint8List> crateApiZkloginSignEphemeral({
    required List<int> secret,
    required List<int> message,
  });

  Future<bool> crateApiZkloginVerifyEphemeral({
    required List<int> pubkey,
    required List<int> message,
    required List<int> signature,
  });

  Future<ZkLoginClaimsData> crateApiZkloginVerifyJwt({
    required String jwt,
    required String jwksJson,
    required String expectedIss,
    required String expectedAud,
    String? expectedNonce,
    required BigInt nowSecs,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiBlake3HashApi({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBlake3HashApiConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBlake3HashApiConstMeta =>
      const TaskConstMeta(debugName: "blake3_hash_api", argNames: ["data"]);

  @override
  Future<KeyPairData> crateApiDeriveKeypairFromMnemonic({
    required String mnemonic,
    required String curveName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveKeypairFromMnemonicConstMeta,
        argValues: [mnemonic, curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveKeypairFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "derive_keypair_from_mnemonic",
        argNames: ["mnemonic", "curveName"],
      );

  @override
  Future<KeyPairData> crateApiDeriveKeypairFromPathApi({
    required String mnemonic,
    required String derivationPath,
    required String curveName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(derivationPath, serializer);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveKeypairFromPathApiConstMeta,
        argValues: [mnemonic, derivationPath, curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveKeypairFromPathApiConstMeta =>
      const TaskConstMeta(
        debugName: "derive_keypair_from_path_api",
        argNames: ["mnemonic", "derivationPath", "curveName"],
      );

  @override
  Future<KeyPairData> crateApiDeriveKeypairFromSeedApi({
    required List<int> seed,
    required String curveName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seed, serializer);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveKeypairFromSeedApiConstMeta,
        argValues: [seed, curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveKeypairFromSeedApiConstMeta =>
      const TaskConstMeta(
        debugName: "derive_keypair_from_seed_api",
        argNames: ["seed", "curveName"],
      );

  @override
  Future<List<KeyPairData>> crateApiDeriveMultipleAddressesApi({
    required String mnemonic,
    required String pathTemplate,
    required String curveName,
    required BigInt count,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(pathTemplate, serializer);
          sse_encode_String(curveName, serializer);
          sse_encode_usize(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_pair_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveMultipleAddressesApiConstMeta,
        argValues: [mnemonic, pathTemplate, curveName, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveMultipleAddressesApiConstMeta =>
      const TaskConstMeta(
        debugName: "derive_multiple_addresses_api",
        argNames: ["mnemonic", "pathTemplate", "curveName", "count"],
      );

  @override
  Future<KeyPairData> crateApiGenerateKeypairApi({required String curveName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateKeypairApiConstMeta,
        argValues: [curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateKeypairApiConstMeta => const TaskConstMeta(
    debugName: "generate_keypair_api",
    argNames: ["curveName"],
  );

  @override
  Future<String> crateApiGenerateMnemonicApi({required BigInt wordCount}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(wordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateMnemonicApiConstMeta,
        argValues: [wordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateMnemonicApiConstMeta =>
      const TaskConstMeta(
        debugName: "generate_mnemonic_api",
        argNames: ["wordCount"],
      );

  @override
  Future<KeyPairData> crateApiImportKeypairFromPrivateKey({
    required String privateKey,
    required String curveName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(privateKey, serializer);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportKeypairFromPrivateKeyConstMeta,
        argValues: [privateKey, curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportKeypairFromPrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "import_keypair_from_private_key",
        argNames: ["privateKey", "curveName"],
      );

  @override
  Future<List<CurveInfo>> crateApiListSupportedCurves() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_curve_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListSupportedCurvesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListSupportedCurvesConstMeta =>
      const TaskConstMeta(debugName: "list_supported_curves", argNames: []);

  @override
  Future<Uint8List> crateApiSignMessageApi({
    required String privateKey,
    required List<int> message,
    required String curveName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(privateKey, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignMessageApiConstMeta,
        argValues: [privateKey, message, curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignMessageApiConstMeta => const TaskConstMeta(
    debugName: "sign_message_api",
    argNames: ["privateKey", "message", "curveName"],
  );

  @override
  Future<bool> crateApiVerifySignatureApi({
    required String address,
    required List<int> message,
    required List<int> signature,
    required String curveName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_list_prim_u_8_loose(signature, serializer);
          sse_encode_String(curveName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVerifySignatureApiConstMeta,
        argValues: [address, message, signature, curveName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifySignatureApiConstMeta => const TaskConstMeta(
    debugName: "verify_signature_api",
    argNames: ["address", "message", "signature", "curveName"],
  );

  @override
  Future<Uint8List> crateApiZkloginBuildBundle({
    required String jwt,
    required String jwksJson,
    required String iss,
    required String aud,
    required List<int> salt,
    required List<int> randomness,
    required List<int> ephemeralPubkey,
    required List<int> ephemeralSig,
    required BigInt maxEpoch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jwt, serializer);
          sse_encode_String(jwksJson, serializer);
          sse_encode_String(iss, serializer);
          sse_encode_String(aud, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          sse_encode_list_prim_u_8_loose(randomness, serializer);
          sse_encode_list_prim_u_8_loose(ephemeralPubkey, serializer);
          sse_encode_list_prim_u_8_loose(ephemeralSig, serializer);
          sse_encode_u_64(maxEpoch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginBuildBundleConstMeta,
        argValues: [
          jwt,
          jwksJson,
          iss,
          aud,
          salt,
          randomness,
          ephemeralPubkey,
          ephemeralSig,
          maxEpoch,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginBuildBundleConstMeta => const TaskConstMeta(
    debugName: "zklogin_build_bundle",
    argNames: [
      "jwt",
      "jwksJson",
      "iss",
      "aud",
      "salt",
      "randomness",
      "ephemeralPubkey",
      "ephemeralSig",
      "maxEpoch",
    ],
  );

  @override
  Future<String> crateApiZkloginDeriveAddress({
    required String iss,
    required String aud,
    required String sub,
    required List<int> salt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(iss, serializer);
          sse_encode_String(aud, serializer);
          sse_encode_String(sub, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginDeriveAddressConstMeta,
        argValues: [iss, aud, sub, salt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginDeriveAddressConstMeta =>
      const TaskConstMeta(
        debugName: "zklogin_derive_address",
        argNames: ["iss", "aud", "sub", "salt"],
      );

  @override
  Future<Uint8List> crateApiZkloginDeterministicSalt({
    required String iss,
    required String aud,
    required String sub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(iss, serializer);
          sse_encode_String(aud, serializer);
          sse_encode_String(sub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginDeterministicSaltConstMeta,
        argValues: [iss, aud, sub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginDeterministicSaltConstMeta =>
      const TaskConstMeta(
        debugName: "zklogin_deterministic_salt",
        argNames: ["iss", "aud", "sub"],
      );

  @override
  Future<ZkLoginNonceData> crateApiZkloginPrepareNonce({
    required BigInt maxEpoch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(maxEpoch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_zk_login_nonce_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginPrepareNonceConstMeta,
        argValues: [maxEpoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginPrepareNonceConstMeta =>
      const TaskConstMeta(
        debugName: "zklogin_prepare_nonce",
        argNames: ["maxEpoch"],
      );

  @override
  Future<Uint8List> crateApiZkloginSignEphemeral({
    required List<int> secret,
    required List<int> message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secret, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginSignEphemeralConstMeta,
        argValues: [secret, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginSignEphemeralConstMeta =>
      const TaskConstMeta(
        debugName: "zklogin_sign_ephemeral",
        argNames: ["secret", "message"],
      );

  @override
  Future<bool> crateApiZkloginVerifyEphemeral({
    required List<int> pubkey,
    required List<int> message,
    required List<int> signature,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pubkey, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_list_prim_u_8_loose(signature, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginVerifyEphemeralConstMeta,
        argValues: [pubkey, message, signature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginVerifyEphemeralConstMeta =>
      const TaskConstMeta(
        debugName: "zklogin_verify_ephemeral",
        argNames: ["pubkey", "message", "signature"],
      );

  @override
  Future<ZkLoginClaimsData> crateApiZkloginVerifyJwt({
    required String jwt,
    required String jwksJson,
    required String expectedIss,
    required String expectedAud,
    String? expectedNonce,
    required BigInt nowSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jwt, serializer);
          sse_encode_String(jwksJson, serializer);
          sse_encode_String(expectedIss, serializer);
          sse_encode_String(expectedAud, serializer);
          sse_encode_opt_String(expectedNonce, serializer);
          sse_encode_u_64(nowSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_zk_login_claims_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkloginVerifyJwtConstMeta,
        argValues: [
          jwt,
          jwksJson,
          expectedIss,
          expectedAud,
          expectedNonce,
          nowSecs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkloginVerifyJwtConstMeta => const TaskConstMeta(
    debugName: "zklogin_verify_jwt",
    argNames: [
      "jwt",
      "jwksJson",
      "expectedIss",
      "expectedAud",
      "expectedNonce",
      "nowSecs",
    ],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CurveInfo dco_decode_curve_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CurveInfo(
      name: dco_decode_String(arr[0]),
      isPostQuantum: dco_decode_bool(arr[1]),
      isHybrid: dco_decode_bool(arr[2]),
      securityLevel: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  KeyPairData dco_decode_key_pair_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return KeyPairData(
      privateKey: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      taggedAddress: dco_decode_String(arr[3]),
      rawPublicKey: dco_decode_list_prim_u_8_strict(arr[4]),
      curveType: dco_decode_String(arr[5]),
    );
  }

  @protected
  List<CurveInfo> dco_decode_list_curve_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_curve_info).toList();
  }

  @protected
  List<KeyPairData> dco_decode_list_key_pair_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_key_pair_data).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ZkLoginClaimsData dco_decode_zk_login_claims_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ZkLoginClaimsData(
      iss: dco_decode_String(arr[0]),
      aud: dco_decode_String(arr[1]),
      sub: dco_decode_String(arr[2]),
      exp: dco_decode_opt_box_autoadd_u_64(arr[3]),
      nonce: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  ZkLoginNonceData dco_decode_zk_login_nonce_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ZkLoginNonceData(
      ephemeralPubkey: dco_decode_list_prim_u_8_strict(arr[0]),
      ephemeralSecret: dco_decode_list_prim_u_8_strict(arr[1]),
      randomness: dco_decode_list_prim_u_8_strict(arr[2]),
      maxEpoch: dco_decode_u_64(arr[3]),
      nonce: dco_decode_String(arr[4]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CurveInfo sse_decode_curve_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_isPostQuantum = sse_decode_bool(deserializer);
    var var_isHybrid = sse_decode_bool(deserializer);
    var var_securityLevel = sse_decode_u_8(deserializer);
    return CurveInfo(
      name: var_name,
      isPostQuantum: var_isPostQuantum,
      isHybrid: var_isHybrid,
      securityLevel: var_securityLevel,
    );
  }

  @protected
  KeyPairData sse_decode_key_pair_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKey = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_taggedAddress = sse_decode_String(deserializer);
    var var_rawPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_curveType = sse_decode_String(deserializer);
    return KeyPairData(
      privateKey: var_privateKey,
      publicKey: var_publicKey,
      address: var_address,
      taggedAddress: var_taggedAddress,
      rawPublicKey: var_rawPublicKey,
      curveType: var_curveType,
    );
  }

  @protected
  List<CurveInfo> sse_decode_list_curve_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CurveInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_curve_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<KeyPairData> sse_decode_list_key_pair_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KeyPairData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_key_pair_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  ZkLoginClaimsData sse_decode_zk_login_claims_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_iss = sse_decode_String(deserializer);
    var var_aud = sse_decode_String(deserializer);
    var var_sub = sse_decode_String(deserializer);
    var var_exp = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_nonce = sse_decode_opt_String(deserializer);
    return ZkLoginClaimsData(
      iss: var_iss,
      aud: var_aud,
      sub: var_sub,
      exp: var_exp,
      nonce: var_nonce,
    );
  }

  @protected
  ZkLoginNonceData sse_decode_zk_login_nonce_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ephemeralPubkey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ephemeralSecret = sse_decode_list_prim_u_8_strict(deserializer);
    var var_randomness = sse_decode_list_prim_u_8_strict(deserializer);
    var var_maxEpoch = sse_decode_u_64(deserializer);
    var var_nonce = sse_decode_String(deserializer);
    return ZkLoginNonceData(
      ephemeralPubkey: var_ephemeralPubkey,
      ephemeralSecret: var_ephemeralSecret,
      randomness: var_randomness,
      maxEpoch: var_maxEpoch,
      nonce: var_nonce,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_curve_info(CurveInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isPostQuantum, serializer);
    sse_encode_bool(self.isHybrid, serializer);
    sse_encode_u_8(self.securityLevel, serializer);
  }

  @protected
  void sse_encode_key_pair_data(KeyPairData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.privateKey, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_String(self.taggedAddress, serializer);
    sse_encode_list_prim_u_8_strict(self.rawPublicKey, serializer);
    sse_encode_String(self.curveType, serializer);
  }

  @protected
  void sse_encode_list_curve_info(
    List<CurveInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_curve_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_key_pair_data(
    List<KeyPairData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_key_pair_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_zk_login_claims_data(
    ZkLoginClaimsData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.iss, serializer);
    sse_encode_String(self.aud, serializer);
    sse_encode_String(self.sub, serializer);
    sse_encode_opt_box_autoadd_u_64(self.exp, serializer);
    sse_encode_opt_String(self.nonce, serializer);
  }

  @protected
  void sse_encode_zk_login_nonce_data(
    ZkLoginNonceData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.ephemeralPubkey, serializer);
    sse_encode_list_prim_u_8_strict(self.ephemeralSecret, serializer);
    sse_encode_list_prim_u_8_strict(self.randomness, serializer);
    sse_encode_u_64(self.maxEpoch, serializer);
    sse_encode_String(self.nonce, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
