[package]
name = "mona-crypto"
edition.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[features]
# Define blake3 as an optional feature that enables the blake3 dependency
blake3 = ["dep:blake3"]  # Define the blake3 feature

[dependencies]
# Core crypto libraries
k256 = { version = "0.13.1", features = ["ecdsa", "std"] }
p256 = { version = "0.13.2", features = ["ecdsa", "std"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
sha3 = "0.10.8"
aes-gcm = "0.10.2"
argon2 = "0.5"

# Make blake3 optional and enabled via the blake3 feature
blake3 = { version = "1.3.1", optional = true }

# BIP39 support
bip39 = { version = "2.0", features = ["rand"] }

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34-deprecated"
bincode = "2.0.1"
toml = "0.8.22"
hex = "0.4.3"

# Utilities
thiserror = "2.0.12"
rand = "0.9.1"
log = "0.4.27"
base64 = "0.22.1"

# Project dependencies
mona-types.workspace = true
common.workspace =true
key.workspace = true
